%YAML:1.2
# SPDX-FileCopyrightText: 2021 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

map:
  dim:                        [10.24, 10.24, 10.24]
  res:                        0.01

data:
  # tsdf
  truncation_boundary_factor: 8
  max_weight:                 100

  # occupancy
  log_odd_min:                -5.015
  log_odd_max:                 5.015
  fs_integr_scale:            1
  const_surface_thickness:    false
  uncertainty_model:          linear
  tau_min_factor:             3
  tau_max_factor:             12
  k_tau:                      0.05
  sigma_min_factor:           1         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:           3         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                    0.05

sensor:
  width:                      640
  height:                     480
  fx:                         600
  fy:                         600
  cx:                         320
  cy:                         240
  near_plane:                 0.4
  far_plane:                  6.0

tracker:
  iterations:                 [10, 5, 4]
  dist_threshold:             0.1
  normal_threshold:           0.8
  track_threshold:            0.15
  icp_threshold:              0.00001

reader:
  reader_type:                "openni"
  sequence_path:              ""
  ground_truth_file:          ""
  fps:                        0.0
  drop_frames:                false
  verbose:                    0

app:
  enable_ground_truth:        false
  enable_rendering:           true
  enable_gui:                 true
  mesh_path:                  "meshes"
  slice_path:                 "meshes"
  structure_path:             "meshes"
  sensor_downsampling_factor: 2
  tracking_rate:              1
  integration_rate:           1
  rendering_rate:             1
  meshing_rate:               0
  max_frames:                 -1
  log_file:                   "log.tsv"

